name: quarto-env
channels:
  - conda-forge
dependencies:
  - python=3.11
  - flask
  - python-dotenv
  - quarto
  - r-base  # R interpreter
  - r-tidyverse
  - r-knitr
  - r-markdown
  - r-irkernel  # enables R kernel in Jupyter/VSCode
