name: quarto-env
channels:
  - conda-forge
  - defaults
dependencies:
  - python              # no version means latest stable 
  - flask
  - python-dotenv
  - r-base
  - r-tidyverse
  - r-knitr
  - r-markdown
  - r-irkernel
  - notebook
  - ipykernel
  - pip
  - pip:
      # additional python packages here if needed
